### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by helen88** [nlsde-safety-team/DualAttentionAttack#1]
Hi,
    I have no idea about where to download the dataset, could you provide a url ?

Thanks.

**Comment by Yzx835** [comment]
Thanks for your interest of our work.
The dataset was generated by CARLA, according to the Section 4.1 in [paper](https://arxiv.org/abs/2103.01050).
You could generate your own dataset using CARLA.

**Comment by helen88** [comment]
Thanks so much.
